import { serverApi } from "@/services/server-api";
import { useOwnerScopeStore } from "@/stores/use-owner-scope-store";
import type { MainImageMedia, MainImagePair, MainImageProduct, MainImageProject, MainImageProjectQuery, MainImageTemplate, MainImageVariant } from "@/types/main-image-replication";

type RawMedia = Partial<MainImageMedia> & { id?: string; mediaId?: string };
function media(raw?: RawMedia): MainImageMedia { const id = raw?.id || raw?.mediaId || ""; return { id, mediaId: raw?.mediaId || id, fileName: raw?.fileName || "媒体文件", mimeType: raw?.mimeType || "image/png", bytes: Number(raw?.bytes || 0), url: raw?.url || "", thumbnailUrl: raw?.thumbnailUrl || raw?.url || "", storageKey: raw?.storageKey || `media:${id}`, width: raw?.width == null ? undefined : Number(raw.width), height: raw?.height == null ? undefined : Number(raw.height) }; }
function variant(raw: any): MainImageVariant { return { id: raw.id || "", pairId: raw.pairId || "", mediaId: raw.mediaId, image: raw.image ? media(raw.image) : undefined, sourceMediaId: raw.sourceMediaId, kind: raw.kind || "retry", status: raw.status || "draft", prompt: raw.prompt || "", resolvedPrompt: raw.resolvedPrompt, activeTaskId: raw.activeTaskId, error: raw.error, revision: Number(raw.revision || 1), createdAt: raw.createdAt || "", updatedAt: raw.updatedAt || "" }; }
function normalize(raw: any): MainImageProject { const product: MainImageProduct = { id: raw.product?.id || raw.productId || "", name: raw.product?.name || "", brand: raw.product?.brand || "", productType: raw.product?.productType || "", material: raw.product?.material || "", sellingPoints: Array.isArray(raw.product?.sellingPoints) ? raw.product.sellingPoints : [], instruction: raw.product?.instruction || "", resultImage: raw.product?.resultImage ? media(raw.product.resultImage) : undefined }; return { id: raw.id || "", ownerId: raw.ownerId || "", ownerUsername: raw.ownerUsername || "", title: raw.title || "", productId: raw.productId || product.id, productMediaId: raw.productMediaId || "", product, productImage: media(raw.productImage || product.resultImage), pairs: (raw.pairs || []).map((item: any, index: number): MainImagePair => ({ id: item.id || "", projectId: raw.id || "", sortOrder: Number(item.sortOrder ?? index), referenceMediaId: item.referenceMediaId || "", referenceImage: media(item.referenceImage), resultMediaId: item.resultMediaId, resultImage: item.resultImage ? media(item.resultImage) : undefined, referenceWidth: Number(item.referenceWidth || 1), referenceHeight: Number(item.referenceHeight || 1), prompt: item.prompt || raw.defaultPrompt || "", resolvedPrompt: item.resolvedPrompt, status: item.status || "draft", activeTaskId: item.activeTaskId, error: item.error, revision: Number(item.revision || 1), modificationVariants: (item.modificationVariants || []).map(variant) })), status: raw.status || "draft", error: raw.error, revision: Number(raw.revision || 1), defaultPrompt: raw.defaultPrompt || "", accessLevel: raw.accessLevel, createdAt: raw.createdAt || "", updatedAt: raw.updatedAt || "" }; }
function unwrap(payload: any) { return normalize(payload.item || payload); }
export async function listMainImageReplicationProjects(query: MainImageProjectQuery = {}) { const params = new URLSearchParams({ owner: query.owner || useOwnerScopeStore.getState().scope, page: String(query.page || 1), pageSize: String(query.pageSize || 20) }); if (query.keyword?.trim()) params.set("keyword", query.keyword.trim()); const result = await serverApi<{ items: any[]; total: number; page: number; pageSize: number }>(`/api/main-image-replication-projects?${params}`); return { ...result, items: result.items.map(normalize) }; }
export async function getMainImageReplicationProject(id: string) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${id}`)); }
export async function createMainImageReplicationProject(input: { productId: string; title?: string; referenceMediaIds: string[] }) { return unwrap(await serverApi<any>("/api/main-image-replication-projects", { method: "POST", body: JSON.stringify(input) })); }
export async function updateMainImageReplicationProject(id: string, input: { revision: number; title: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${id}`, { method: "PATCH", body: JSON.stringify(input) })); }
export async function updateMainImageReplicationPair(projectId: string, pairId: string, input: { revision: number; prompt: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}`, { method: "PATCH", body: JSON.stringify(input) })); }
export async function generateMainImageReplication(projectId: string, input: { revision?: number; model: string; channelId: string; clientRequestIdPrefix?: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/generate`, { method: "POST", body: JSON.stringify(input) })); }
export async function generateMainImageReplicationPair(projectId: string, pairId: string, input: { revision?: number; model: string; channelId: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/generate`, { method: "POST", body: JSON.stringify(input) })); }
export async function cancelMainImageReplicationPair(projectId: string, pairId: string) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/cancel`, { method: "POST", body: "{}" })); }
export async function setMainImageReplicationPairResult(projectId: string, pairId: string, input: { revision: number; status: "running" | "succeeded" | "failed" | "interrupted"; mediaId?: string; error?: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/result`, { method: "POST", body: JSON.stringify(input) })); }
export async function createMainImageReplicationVariant(projectId: string, pairId: string, input: { revision: number; kind: "retry" | "mask_edit"; mode: "remote" | "personal"; model?: string; channelId?: string; sourceMediaId?: string; maskMediaId?: string; prompt?: string }) { const result = await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/variants`, { method: "POST", body: JSON.stringify(input) }); return { project: unwrap(result), variantId: result.variantId || "" }; }
export async function setMainImageReplicationVariantResult(projectId: string, pairId: string, variantId: string, input: { revision: number; status: "succeeded" | "failed" | "interrupted"; mediaId?: string; error?: string }) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/variants/${variantId}/result`, { method: "POST", body: JSON.stringify(input) })); }
export async function promoteMainImageReplicationVariant(projectId: string, pairId: string, variantId: string, revision: number) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/variants/${variantId}/promote`, { method: "POST", body: JSON.stringify({ revision }) })); }
export async function cancelMainImageReplicationVariant(projectId: string, pairId: string, variantId: string) { return unwrap(await serverApi<any>(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/variants/${variantId}/cancel`, { method: "POST", body: "{}" })); }
export async function deleteMainImageReplicationVariant(projectId: string, pairId: string, variantId: string) { await serverApi(`/api/main-image-replication-projects/${projectId}/pairs/${pairId}/variants/${variantId}`, { method: "DELETE" }); }
export async function deleteMainImageReplicationProject(id: string) { await serverApi(`/api/main-image-replication-projects/${id}`, { method: "DELETE" }); }
