import { serverApi } from "@/services/server-api";
import { useOwnerScopeStore } from "@/stores/use-owner-scope-store";
import type { MainImageMedia, MainImageTemplate } from "@/types/main-image-replication";
function media(raw: any): MainImageMedia | undefined { if (!raw) return undefined; const id = raw.id || raw.mediaId || ""; return { id, mediaId: raw.mediaId || id, fileName: raw.fileName || "媒体文件", mimeType: raw.mimeType || "image/png", bytes: Number(raw.bytes || 0), url: raw.url || "", thumbnailUrl: raw.thumbnailUrl || raw.url || "", storageKey: raw.storageKey || `media:${id}`, width: raw.width, height: raw.height }; }
function normalize(raw: any): MainImageTemplate { const references = (raw.references || []).map((item: any) => ({ id: item.id || "", mediaId: item.mediaId || item.image?.mediaId || "", sortOrder: Number(item.sortOrder || 0), image: media(item.image) })); return { id: raw.id || "", ownerId: raw.ownerId || "", ownerUsername: raw.ownerUsername, name: raw.name || "", revision: Number(raw.revision || 1), referenceCount: Number(raw.referenceCount || references.length), coverImage: media(raw.coverImage || references[0]?.image), references, accessLevel: raw.accessLevel, createdAt: raw.createdAt || "", updatedAt: raw.updatedAt || "" }; }
export async function listMainImageReplicationTemplates() { const result = await serverApi<{ items?: any[] }>(`/api/main-image-replication-templates?owner=${useOwnerScopeStore.getState().scope}`); return (Array.isArray(result.items) ? result.items : []).map(normalize); }
export async function getMainImageReplicationTemplate(id: string) { return normalize((await serverApi<any>(`/api/main-image-replication-templates/${id}`)).item); }
export async function createMainImageReplicationTemplate(input: { ownerId?: string; name: string; referenceMediaIds: string[] }) { return normalize((await serverApi<any>("/api/main-image-replication-templates", { method: "POST", body: JSON.stringify(input) })).item); }
export async function updateMainImageReplicationTemplate(id: string, input: { revision: number; name?: string; referenceMediaIds?: string[] }) { return normalize((await serverApi<any>(`/api/main-image-replication-templates/${id}`, { method: "PATCH", body: JSON.stringify(input) })).item); }
export async function deleteMainImageReplicationTemplate(id: string, revision: number) { await serverApi(`/api/main-image-replication-templates/${id}`, { method: "DELETE", body: JSON.stringify({ revision }) }); }
